services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: inventario
      POSTGRES_PASSWORD: inventario
      POSTGRES_DB: inventario
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
